---

version: '3.6'

services:
  app:
    build: .
    command: ng serve --host 0.0.0.0
    ports:
      - 4200:4200
      - 49153:49153
    expose:
      - 4200
      - 49153
    volumes:
      - .:/app
